# Generated by Django 2.2.13 on 2020-06-18 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20200618_1815"),
        ("checkout", "0002_auto_20200618_1815"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp_created", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellerorder_order",
                        to="checkout.Order",
                    ),
                ),
                (
                    "seller",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellerorder_seller",
                        to="home.SellerProfile",
                    ),
                ),
            ],
        ),
    ]
