# Generated by Django 2.2.13 on 2020-06-22 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0005_auto_20200622_1622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
