# Generated by Django 2.2.13 on 2020-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_auto_20200622_1620"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_reviewer",
                to="home.CustomerProfile",
            ),
        ),
    ]
