# Generated by Django 2.2.13 on 2020-06-22 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("item", "0006_auto_20200622_1624"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="seller_profile",),
        migrations.AddField(
            model_name="item",
            name="seller",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_seller",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="seller",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_seller",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
