# Generated by Django 2.2.13 on 2020-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200618_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='reviews',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
