# Generated by Django 2.2.13 on 2020-06-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20200618_1815"),
    ]

    operations = [
        migrations.RemoveField(model_name="customerprofile", name="user",),
    ]
