# Generated by Django 2.2.13 on 2020-06-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20200622_1648'),
        ('home', '0006_remove_customerprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='timestamp_created',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_item', to='item.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_review', to='item.Review')),
            ],
        ),
    ]
