# Generated by Django 2.2.13 on 2020-06-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20200622_1648'),
        ('checkout', '0007_auto_20200622_1648'),
        ('home', '0007_auto_20200622_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellerlistings_listing', to='item.Item')),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recentlyviewed_item', to='item.Item')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customerpurchases_order', to='checkout.Order')),
            ],
        ),
    ]
