# Generated by Django 2.2.13 on 2020-06-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200622_1620"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="address",),
        migrations.RemoveField(model_name="user", name="photo",),
    ]
