# Generated by Django 2.2.13 on 2020-06-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customerpurchases_recentlyviewed_sellerlistings'),
        ('users', '0005_auto_20200622_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_listings', to='home.SellerListings'),
        ),
        migrations.AddField(
            model_name='user',
            name='purchases',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_purchases', to='home.CustomerPurchases'),
        ),
        migrations.AddField(
            model_name='user',
            name='recently_viewed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recently_viewed', to='home.RecentlyViewed'),
        ),
    ]
